/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.*;

public class Library {
    public boolean someLibraryMethod()
    {
        return true;
    }

    public int add(int numOne, int numTwo) {
        return numOne + numTwo;
    }

    public int[] roll (int n){

        Random rando = new Random();

        int[] rolls = new int[n];

        for (int i = 0; i < n; i++) {
            int randoNum = rando.nextInt(6);
            rolls[i] = randoNum + 1;
        }
        return rolls;
    }

    public boolean containsDuplicates (int[] arr) {
        for (int i = 0; i < arr.length; i++){
            for (int j = 1; j < arr.length; j++){
                if (i == j) continue;
                if (arr[i] == arr[j])
                    return true;
            }
        }
        return false;
    }

    double sum = 0;
    double counter = 0;
    public double average (double[] arr) {
        for (double num : arr){
            sum += num;
            counter++;
        }
        return Math.ceil(sum / counter) ;
    }

    public double arrayOfArrays (double[][] arr) {
        double[] averages = new double[arr.length];
        for (int i = 0; i < arr.length; i++){
            for (int j = 0; j < arr[i].length; j++){
                sum += arr[i][j];
                counter++;
            }
            averages[i] = sum / counter;
        }

        double minValue = averages[0];
        for (double average : averages) {
            if (average < minValue) {
                minValue = average;
            }
        }
        return minValue ;
    }

    public int getMin (List<Integer> unique) {
        int minValue = (int) unique.get(0);
        for (int i = 0; i < unique.stream().count(); i++) {
            if ((int) unique.get(0) < minValue ) {
                minValue = (int) unique.get(0);
            }
        }
        return minValue ;
    }
    public int getMax (List<Integer> unique) {
        int maxValue = (int) unique.get(0);

        for (int i = 0; i < unique.stream().count(); i++) {
            if ((int) unique.get(i) > maxValue) {
                maxValue = (int) unique.get(i);
            }
        }
        return maxValue;
    }
    public void minMaxTemp (int [][] arr) {
        Map<Integer, Integer> map = new LinkedHashMap<>();

        for (int[] row : arr)
            for (int col : row)
                map.put(col, map.getOrDefault(col, 0) + 1);

        List<Integer> unique = new ArrayList<>();

        for (Map.Entry<Integer, Integer> entry : map.entrySet())
            if (entry.getValue() == 1)
                unique.add(entry.getKey());

        Collections.sort(unique);
        System.out.println("minMaxTemp() unique values: " + unique);
        int maxTemp  = getMax(unique);
        int minTemp = getMin(unique);
        System.out.println("High: " + getMax(unique));
        System.out.println("Low: " + getMin(unique));
        for (int temp : unique) {
            if (temp != minTemp && temp <= maxTemp) {
                System.out.println(minTemp);
                minTemp++;
            }
            if (temp == minTemp && temp <= maxTemp) {
                minTemp++;
            }
        }
    }

    public String tally (List<String> arr) {
        Map<String, Integer> votesMap = new LinkedHashMap<>();

        for (String vote : arr)
        {
            if (votesMap.containsKey(vote))
            {
                int numOfTimes = votesMap.get(vote);
                votesMap.put(vote, numOfTimes + 1);
            }
            else
            {
                votesMap.put(vote, 1);
            }
        }
        System.out.println("tall() Votes: " + votesMap);
        return Collections.max(votesMap.entrySet(), Comparator.comparingInt(Map.Entry::getValue)).getKey();
    }
}
