/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileReader;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
       String file = "app/src/main/resources/gates.js";
        System.out.println(linter(file));

    }

    public static String linter (String file){
        int lineCounter = 0;
        StringBuilder errorMessage = new StringBuilder();
      try {
          Path filePath = Paths.get(file);
          Scanner scanner = new Scanner(new BufferedReader(new FileReader(file)));

          while(scanner.hasNextLine()){
              lineCounter++;
              String string = scanner.nextLine();
              if (string.isEmpty() || string.endsWith("{") || string.endsWith("}") || string.endsWith(";") || string.contains("if") || string.contains("else")) {
                  continue;
              }

              else {
                  errorMessage.append("Line ").append(lineCounter).append(": Missing semicolon.\n");
              }
          }
      }catch (Exception e){
          System.out.println(e + "Error Line" + lineCounter);
      }
      if (errorMessage.length() == 0){
          errorMessage.append("File is empty!");
      }
        return errorMessage.toString();
    }

}