/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void testRestaurantConstructor() {
        Restaurant testRestaurant = new Restaurant("Mcdonalds", 1);
        assertEquals(
                "Mcdonalds",
                "Mcdonalds",
                testRestaurant.getName()
        );
    }

    @Test
    public void testReviewConstructor() {
        Review CheckReview = new Review("good food and great service", "jallow", 4);
        System.out.println(CheckReview);
        assertTrue(true);
    }

    @Test
    public void testReviewConstructor2() {
        Restaurant restaurant = new Restaurant("Chipotle", 1);
        Review checkReview = new Review("good food and great service", "John", 4, restaurant);
        System.out.println(checkReview);
        assertTrue(true);
    }

    @Test
    public void testAddReview_AddOneReview() {
        Restaurant testRestaurant = new Restaurant("Mcdonalds", 1);
        Review review = new Review("This restaurant was good", "Tony", 4, testRestaurant);
        testRestaurant.addReview(review);
        System.out.println(testRestaurant);
        assertEquals( "Mcdonalds has a rating of 4.0 stars and is a $ price point", testRestaurant.toString()
        );
    }

}

