/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test
    public void testRestaurantConstructor() {
        Restaurant firstRestaurant = new Restaurant("Wendy", 3.8, 64.5);
        System.out.println(firstRestaurant);
        assertTrue(true);
    }

    @Test
    public void testReviewConstructor() {
        Review CheckReview = new Review ( true ,"good food and great service", "jallow",4.3 );
        System.out.println(CheckReview);
        assertTrue(true);
    }

}



